sudo: false
language: ruby
cache: bundler
rvm:
  - 3.0.0
branches:
  only:
    - jekyll
    - /^deploy-.*$/
script: bundle exec rake travis
env:
  global:
    secure: KLuKTR30DpaXXh3Vr0LoSYhXn7OsPL/yR5yoRUKB7C6MKxPFt+5gHzdPbXcx/hrcheXkQad4elxkco8qQiKWe4hNeorQFssbsvVSe2P5s2GMaYJma+WdEwDlYwsjpP98xIQ4v5vRamXehfpB8jy/n+mlvdGAIiXA/d1ka9BpkJI=
