language: ruby
cache: bundler
rvm:
- 2.2.0
branches:
  only:
  - jekyll
before_script: bundle exec rspec spec
script: bundle exec rake build
after_success: bundle exec rake release
env:
  global:
    secure: KLuKTR30DpaXXh3Vr0LoSYhXn7OsPL/yR5yoRUKB7C6MKxPFt+5gHzdPbXcx/hrcheXkQad4elxkco8qQiKWe4hNeorQFssbsvVSe2P5s2GMaYJma+WdEwDlYwsjpP98xIQ4v5vRamXehfpB8jy/n+mlvdGAIiXA/d1ka9BpkJI=
