name: 루비 프로그래밍 언어 한글 문서
url: https://ruby-korea.github.io
markdown: kramdown
highlighter: pygments
timezone: Asia/Seoul
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor
- .travis.yml
- .rspec
- .gitignore
- spec
