name: 루비 프로그래밍 언어 한국어 문서
url: https://rubykr.github.io
markdown: kramdown
highlighter: pygments
timezone: Asia/Seoul
cache: bundler
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor
- .travis.yml
- .rspec
- .gitignore
- spec
