name: Build Test

on:
  pull_request:
    branches:
      - jekyll

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Test
        run: bundle exec rake test
      - name: Gen page
        run: bundle exec rake build
